<?php
$lang = array(
   "Home" => "Home",
   "About" => "About",
   "Impact" => "Impact",
   "Help" => "Help",
   "App" => "Our App",
   "Contact" => "Contact",
   "heroText" => "Protecting Our Valleys, Saving Our Seas",
   "heroTextp" => "Smart Net stops waste in valleys before it pollutes the ocean. Together, we can protect marine life and create a cleaner planet",
   "landingBtn1" => "Get Involved",
   "landingBtn2" => "Learn More",
   "mission" => "Our Mission",
   "missionP" => "Smart Net is an innovative solution designed to stop waste from reaching the ocean. Using advanced net technology, Smart Net intercepts garbage in valleys and waterways, preventing pollution at its source. Our goal is simple: protect marine ecosystems and keep our waters clean through smart, efficient, and sustainable solutions.",
   "team" => "Check Our Team !",
   "Valleys Cleaned" => "Valleys Cleaned",
   "Garbage Collected" => "Garbage Collected",
   "People Voluntered" => "People Voluntered",
   "Water Saved" => "Water Saved",
   "Volunteer" => "Volunteer",
   "VolunteerP" => "Help protect our environment by joining cleanup events and making a difference in our valleys.",
   "Donate" => "Donate",
   "DonateP" => "Your donation supports projects to protect valleys and promote environmental awareness.",
   "ReportBtn" => "Report",
   "Report" => "Report A Valley",
   "ReportP" => "Report pollution or concerns in valleys to help us take quick action for restoration.",
   "Try Our App !" => "Try Our App !",
   "TryP" => "Experience Smart Net on the go! Download our app and stay connected to real-time updates, environmental initiatives, and innovative solutions to protect our valleys. Join us in making a lasting impact with just a tap.",
   "Get In Touch With Us" => "Get In Touch With Us",
   "TouchP" => "We'd love to hear from you! Whether you have questions, suggestions, or just want to share your thoughts, feel free to reach out. Our team is here to help and connect with you.",
   "Hammamet" => "Hammamet",
   "Business Hours" => "Business Hours: From 9:00 To 18:00",
   "+216 xxxxxxxx" => "+216 xxxxxxxx",
   "Send" => "Send",

);
